#pragma once

namespace gathra::gateway {

inline constexpr char kDashboardHtml[] = R"GTHHTML(<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GATHRA Gateway</title><style>
:root{color-scheme:dark;--bg:#0c151b;--card:#13242d;--line:#29434f;--accent:#4fc3a1;--warn:#ffbd5a;--bad:#ff6b6b;--text:#e8f2f4;--muted:#9ab1b9}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px system-ui,sans-serif}header{padding:18px 22px;background:#10212a;position:sticky;top:0;z-index:2;border-bottom:1px solid var(--line)}h1{margin:0;font-size:21px}header small{color:var(--muted)}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(340px,1fr));gap:14px;padding:14px}.card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px;min-width:0}.wide{grid-column:1/-1}h2{font-size:16px;margin:0 0 10px;color:var(--accent)}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#0b171d;border-radius:7px;padding:10px;max-height:360px;overflow:auto;color:#cfe1e5}.status{font-weight:700}.ok{color:var(--accent)}.warn{color:var(--warn)}.bad{color:var(--bad)}form{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}label{display:flex;flex-direction:column;gap:4px;color:var(--muted)}input,button{border:1px solid var(--line);border-radius:6px;padding:9px;background:#0c1920;color:var(--text)}button{cursor:pointer;background:#1c4a46;border-color:#347268}button.danger{background:#592d31;border-color:#8c444c}.full{grid-column:1/-1}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:9px}.actions button{flex:1;min-width:110px}#notice{position:fixed;right:14px;bottom:14px;max-width:440px;background:#213741;padding:10px 14px;border-radius:7px;display:none;z-index:5}.kv{display:grid;grid-template-columns:minmax(130px,1fr) 1.4fr;gap:5px 10px}.kv div:nth-child(odd){color:var(--muted)}.kv div:nth-child(even){overflow-wrap:anywhere}progress{width:100%}
</style></head><body><header><h1>GATHRA Gateway</h1><small>Field operations dashboard · v1 has no application-level dashboard authentication</small></header><main>
<section class="card"><h2>Gateway Status</h2><div id="gateway" class="kv"></div></section>
<section class="card"><h2>Wi-Fi</h2><div id="wifi" class="kv"></div><form id="wifiForm"><label>SSID<input name="ssid" maxlength="32" required></label><label>Password (blank retains)<input name="password" type="password" maxlength="64"></label><label class="full"><span><input name="clearPassword" type="checkbox" value="true"> clear stored password (open WLAN)</span></label><button class="full">Save & reconnect</button></form><div class="actions"><button data-post="/api/wifi/reconnect">Reconnect STA</button></div></section>
<section class="card"><h2>Node Pairing</h2><div id="pairing" class="kv"></div><div class="actions"><button data-post="/api/pair/start">Start Pairing</button><button data-post="/api/pair/confirm">Confirm Pairing</button><button data-post="/api/pair/cancel">Cancel</button></div><form id="manualPairForm"><label class="full">Manual Node ID<input name="nodeId" maxlength="24" pattern="[A-Za-z0-9_-]{1,24}" required></label><button class="full">Manual Pair</button></form><div class="actions"><button id="unpair" class="danger">Unpair</button></div></section>
<section class="card"><h2>Latest Node Telemetry</h2><div id="telemetry" class="kv"></div></section>
<section class="card wide"><h2>LoRa Diagnostics</h2><div id="radio" class="kv"></div><form id="radioForm"><label>Frequency MHz<input name="frequencyMhz" type="number" step="0.001" min="410" max="525"></label><label>Bandwidth kHz<input name="bandwidthKhz" type="number" step="0.01"></label><label>Spreading factor<input name="spreadingFactor" type="number" min="7" max="12"></label><label>Coding rate denominator<input name="codingRateDenominator" type="number" min="5" max="8"></label><label>TX power dBm<input name="txPowerDbm" type="number" min="2" max="20"></label><label>Sync word<input name="syncWord" type="number" min="0" max="255"></label><button class="full">Validate & apply</button></form><div class="actions"><button data-post="/api/radio/restart">Restart Radio</button></div></section>
<section class="card"><h2>Durable Queue</h2><div id="queue" class="kv"></div><progress id="queueProgress" max="100"></progress><div class="actions"><button data-post="/api/queue/flush">Flush Queue Now</button></div></section>
<section class="card"><h2>Backend</h2><div id="backend" class="kv"></div><form id="backendForm"><label class="full">Base URL<input name="baseUrl" maxlength="160" required></label><label class="full">Bearer token (blank retains)<input name="token" type="password" maxlength="128"></label><label>Batch size<input name="batchSize" type="number" min="1" max="50"></label><label>HTTP timeout ms<input name="timeoutMs" type="number" min="1000" max="30000"></label><label class="full"><span><input name="clearToken" type="checkbox" value="true"> clear stored token</span></label><button class="full">Save backend settings</button></form><div class="actions"><button data-post="/api/backend/test">Test Backend</button></div></section>
<section class="card"><h2>NTP / Time</h2><div id="time" class="kv"></div></section>
<section class="card"><h2>Gateway Identity</h2><form id="gatewayForm"><label class="full">Logical Gateway ID<input name="gatewayId" maxlength="48" pattern="[A-Za-z0-9_-]{1,48}" required></label><button class="full">Save identity</button></form></section>
<section class="card"><h2>OTA</h2><div id="ota" class="kv"></div><form id="otaForm" action="/api/ota" method="post" enctype="multipart/form-data"><label class="full">Firmware .bin<input name="firmware" type="file" accept=".bin,application/octet-stream" required></label><button class="full">Upload inactive slot & reboot</button></form></section>
<section class="card"><h2>Controls</h2><div class="actions"><button id="reboot" class="danger">Reboot Gateway</button></div></section>
<section class="card wide"><h2>Recent Logs</h2><pre id="logs">Loading…</pre></section>
</main><div id="notice"></div><script>
const $=id=>document.getElementById(id);const pretty=v=>v===null?'unavailable':typeof v==='boolean'?(v?'yes':'no'):String(v);function render(id,obj){const e=$(id);e.textContent='';for(const [k,v] of Object.entries(obj||{})){const a=document.createElement('div'),b=document.createElement('div');a.textContent=k;b.textContent=typeof v==='object'&&v!==null?JSON.stringify(v):pretty(v);e.append(a,b)}}
function notice(message,bad=false){const n=$('notice');n.textContent=message;n.style.display='block';n.className=bad?'bad':'ok';setTimeout(()=>n.style.display='none',5000)}
async function post(path,body=''){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const t=await r.text();if(!r.ok)throw Error(t||r.status);notice(t||'OK');await refresh()}
async function refresh(){try{const s=await fetch('/api/status',{cache:'no-store'}).then(r=>r.json());render('gateway',s.gateway);render('wifi',s.wifi);render('pairing',s.pairing);render('telemetry',s.latestTelemetry);render('radio',s.radio);render('queue',s.queue);render('backend',s.backend);render('time',s.time);render('ota',s.ota);$('queueProgress').value=s.queue.utilizationPercent||0;for(const [form,values] of [['wifiForm',{ssid:s.wifi.configuredSsid}],['gatewayForm',{gatewayId:s.gateway.gatewayId}],['radioForm',s.radio.configuration],['backendForm',{baseUrl:s.backend.baseUrl,batchSize:s.backend.batchSize,timeoutMs:s.backend.timeoutMs}]])for(const [k,v] of Object.entries(values||{})){const x=$(form).elements[k];if(x&&document.activeElement!==x)x.value=v??''}const logs=await fetch('/api/logs',{cache:'no-store'}).then(r=>r.json());$('logs').textContent=logs.entries.map(x=>`[${x.uptimeMs}ms][${x.level}][${x.subsystem}] ${x.message}`).join('\n')||'No logs';}catch(e){notice(e.message,true)}}
for(const b of document.querySelectorAll('[data-post]'))b.onclick=()=>post(b.dataset.post).catch(e=>notice(e.message,true));for(const [id,path] of [['wifiForm','/api/wifi'],['manualPairForm','/api/pair/manual'],['radioForm','/api/radio'],['backendForm','/api/backend'],['gatewayForm','/api/gateway']])$(id).onsubmit=e=>{e.preventDefault();post(path,new URLSearchParams(new FormData(e.target))).catch(x=>notice(x.message,true))};$('unpair').onclick=()=>{if(confirm('Unpair the production Node? New telemetry will not be ACKed until paired again.'))post('/api/pair/unpair','confirm=UNPAIR').catch(e=>notice(e.message,true))};$('reboot').onclick=()=>{if(confirm('Reboot Gateway now?'))post('/api/reboot','confirm=REBOOT').catch(e=>notice(e.message,true))};$('otaForm').onsubmit=async e=>{e.preventDefault();if(!confirm('Telemetry capture is unavailable during OTA/reboot. Continue?'))return;try{const r=await fetch('/api/ota',{method:'POST',body:new FormData(e.target)});const t=await r.text();if(!r.ok)throw Error(t);notice(t)}catch(x){notice(x.message,true)}};refresh();setInterval(refresh,5000);
</script></body></html>)GTHHTML";

}  // namespace gathra::gateway
